name: demos
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _py-xgboost-mutex=2.0
  - absl-py=2.2.0
  - adagio=0.2.6
  - adwaita-icon-theme=48.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.16
  - aiosignal=1.3.2
  - aom=3.9.1
  - appdirs=1.4.4
  - appnope=0.1.4
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - atk-1.0=2.38.0
  - attrs=25.3.0
  - aws-c-auth=0.8.7
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.1
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.5
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.1
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bokeh=3.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.1.31
  - cairo=1.18.4
  - cctools_osx-arm64=1010.6
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - clang=18.1.8
  - clang-18=18.1.8
  - clang_impl_osx-arm64=18.1.8
  - clang_osx-arm64=18.1.8
  - clangxx=18.1.8
  - clangxx_impl_osx-arm64=18.1.8
  - clangxx_osx-arm64=18.1.8
  - click=8.1.8
  - cloudpickle=3.1.1
  - cmdstan=2.36.0
  - cmdstanpy=1.2.5
  - colorama=0.4.6
  - comm=0.2.2
  - compiler-rt=18.1.8
  - compiler-rt_osx-arm64=18.1.8
  - contourpy=1.3.1
  - coreforecast=0.0.16
  - cpython=3.10.16
  - cycler=0.12.1
  - cytoolz=1.0.1
  - darts=0.2
  - dask=2025.3.0
  - dask-core=2025.3.0
  - datasets=2.14.4
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - dill=0.3.7
  - distributed=2025.3.0
  - epoxy=1.5.10
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fs=2.4.16
  - fsspec=2025.3.2
  - fugue=0.9.1
  - gdk-pixbuf=2.42.12
  - gflags=2.2.2
  - giflib=5.2.2
  - glib-tools=2.84.0
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - graphviz=12.2.1
  - grpcio=1.71.0
  - gtk3=3.24.43
  - gts=0.7.6
  - h2=4.2.0
  - harfbuzz=11.0.1
  - hicolor-icon-theme=0.17
  - holidays=0.70
  - hpack=4.1.0
  - huggingface_hub=0.30.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.35.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kaldi=5.5.1112
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld64_osx-arm64=951.9
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libcxx=20.1.2
  - libcxx-devel=18.1.8
  - libde265=1.0.15
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgd=2.3.3
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.84.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.23.1
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm18=18.1.8
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.20.0
  - libopentelemetry-cpp-headers=1.20.0
  - libparquet=19.0.1
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libutf8proc=2.10.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxgboost=2.1.4
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - llvm-tools=18.1.8
  - llvm-tools-18=18.1.8
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.10.0
  - macosx_deployment_target_osx-arm64=11.0
  - make=4.4.1
  - markdown=3.6
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.3.2
  - multiprocess=0.70.15
  - munkres=1.1.4
  - narwhals=1.34.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - nomkl=1.0
  - numba=0.61.2
  - numpy=1.26.4
  - openfst=1.8.3
  - openjpeg=2.5.3
  - openssl=3.5.0
  - optree=0.15.0
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.3
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - platformdirs=4.3.7
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.50
  - propcache=0.2.1
  - prophet=1.1.5
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.4
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.6.0
  - pytz=2024.1
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - rav1e=0.6.6
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=78.1.0
  - sigtool=0.1.3
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - stack_data=0.6.3
  - stanio=0.5.1
  - statsforecast=2.0.1
  - statsmodels=0.14.4
  - stumpy=1.13.0
  - svt-av1=3.0.2
  - sympy=1.13.3
  - tapi=1300.6.5
  - tbb=2022.1.0
  - tbb-devel=2022.1.0
  - tblib=3.1.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - tensorboardx=2.6.2.2
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toolz=1.0.0
  - torchaudio=2.6.0
  - torchvision=0.21.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - triad=0.9.8
  - tsfresh=0.21.0
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - utilsforecast=0.2.12
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x265=3.5
  - xgboost=2.1.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - xyzservices=2025.1.0
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
